// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TBSExam.Data.ExamContext;

#nullable disable

namespace TBSExam.Data.Migrations
{
    [DbContext(typeof(ExamContextConnection))]
    [Migration("20231117004853_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TBSExam.Models.Models.Bitacora", b =>
                {
                    b.Property<int>("shipment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipment_id"));

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("shipment_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("shipment_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("TBSExam.Models.Models.Folio", b =>
                {
                    b.Property<string>("folio_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("disponible")
                        .HasColumnType("bit");

                    b.HasKey("folio_id");

                    b.ToTable("Folios");
                });

            modelBuilder.Entity("TBSExam.Models.Models.Pedido", b =>
                {
                    b.Property<int>("pedido_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pedido_id"));

                    b.Property<string>("articulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("folio_id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("pedido_id");

                    b.HasIndex("folio_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TBSExam.Models.Models.Usuario", b =>
                {
                    b.Property<int>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuario_id"));

                    b.Property<string>("cveUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("numAcceso")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ultimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("usuPwd")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("usuario_id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TBSExam.Models.Models.Bitacora", b =>
                {
                    b.HasOne("TBSExam.Models.Models.Usuario", "usuario")
                        .WithMany("bitacora")
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TBSExam.Models.Models.Pedido", b =>
                {
                    b.HasOne("TBSExam.Models.Models.Folio", "folio")
                        .WithMany("pedido")
                        .HasForeignKey("folio_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TBSExam.Models.Models.Usuario", "usuario")
                        .WithMany("pedido")
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("folio");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TBSExam.Models.Models.Folio", b =>
                {
                    b.Navigation("pedido");
                });

            modelBuilder.Entity("TBSExam.Models.Models.Usuario", b =>
                {
                    b.Navigation("bitacora");

                    b.Navigation("pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
